resources:
  - name: s3-resource
    type: s3
    source:
      bucket: concourse
      endpoint: http://192.168.1.84:9000
      regexp: algorithm/(.*)
      access_key_id: miniouser
      secret_access_key: miniopwd

jobs:
  - name: job-minio-s3-object
    plan:
      - get: s3-resource
      - task: task-minio-s3-object
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ubuntu
          inputs:
            - name: s3-resource
          run:
            path: sh
            args:
              - -exc
              - |
                ls -lh
                cat s3-resource/url
                cat s3-resource/version